export enum Variables {
  weathercode = "weathercode",
  temperature_2m_max = "temperature_2m_max",
  temperature_2m_min = "temperature_2m_min",
  apparent_temperature_max = "apparent_temperature_max",
  apparent_temperature_min = "apparent_temperature_min",
  sunrise = "sunrise",
  sunset = "sunset",
  precipitation_sum = "precipitation_sum",
  showers_sum = "showers_sum",
  precipitation_hours = "precipitation_hours",
  windspeed_10m_max = "windspeed_10m_max",
  windgusts_10m_max = "windgusts_10m_max",
  winddirection_10m_dominant = "winddirection_10m_dominant",
  shortwave_radiation_sum = "shortwave_radiation_sum",
  et0_fao_evapotranspiration = "et0_fao_evapotranspiration",
  rain_sum = "rain_sum",
  snowfall_sum = "snowfall_sum",
}